branches:
  - master
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'
  - - '@pubgcorp/semantic-release-helm'
    - chartRepository: "https://github.com/hajle-silesia/app-test-config"
      ociRegistry: "registry-1.docker.io"
      chartDirectory: "./charts/app-test"
      versionUpdatePolicy: sync
      appVersionUpdatePolicy: fixed