branches:
  - master
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'
  - - '@pubgcorp/semantic-release-helm'
    - ociRegistry: "docker.io/mtweeman/hajle-silesia_app-test-config"
      chartDirectory: "./charts/app-test"
      versionUpdatePolicy: sync
      appVersionUpdatePolicy: fixed