name: CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Chart build
    uses: hajle-silesia/app-test-config/.github/workflows/shared-chart-build.yaml@master
    with:
      chart-dir: charts/app-test
      docker-hub-username: ${{ secrets.DOCKER_HUB_USERNAME }}
    secrets:
      docker-hub-token: ${{ secrets.DOCKER_HUB_TOKEN }}
