name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Prevent semantic-release from making changes by "github-actions" user as it doesn't trigger other workflows
          # Source: https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions#pushing-package.json-changes-to-your-repository
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - name: Install dependencies
        run: npm install -D @pubgcorp/semantic-release-helm
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Set up semantic-release
        run: |
          echo "${HELM_REGISTRY_USERNAME}"
          npx semantic-release@24.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
          HELM_REGISTRY_USERNAME: ${{ secrets.DOCKER_USER }}
          HELM_REGISTRY_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
