name: Shared chart build

on:
  workflow_call:
    inputs:
      docker-hub-registry:
        description: Docker Hub registry
        type: string
        required: false
        default: registry-1.docker.io
      chart-dir:
        description: Directory containing Chart.yaml
        type: string
        required: true
    secrets:
      docker-hub-username:
        description: Docker Hub username
        required: true
      docker-hub-token:
        description: Docker Hub token
        required: true

permissions:
  contents: read

jobs:
  shared-chart-build:
    name: Shared chart build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Helm meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            mtweeman/hajle-silesia_app-test-config
          tags: |
            type=semver,pattern={{version}}
          flavor: |
            latest=false
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        run: |
          echo "${{ secrets.docker-hub-token }}" | helm registry login ${{ inputs.docker-hub-registry }} \
            --username ${{ secrets.docker-hub-username }} \
            --password-stdin
      - name: Package
        id: package
        run: |
          response=$(helm package ${{ inputs.chart-dir }} \
            --version ${{ steps.meta.outputs.version }})
          chart_archive_file=$(basename "${response}")
          echo "${chart_archive_file}"
          echo "chart-archive-file=$chart_archive_file" >> $GITHUB_OUTPUT
      - name: Publish
        if: github.event_name != 'pull_request'
        run: |
          echo PUSTO
          echo ${{ steps.package.outputs.chart-archive-file }}
          echo ${{ inputs.docker-hub-registry }}
          echo PUSTO
          helm push ${{ steps.package.outputs.chart-archive-file }} \
            oci://${{ inputs.docker-hub-registry }}/mtweeman
