name: Shared chart build

on:
  workflow_call:
    inputs:
      docker-hub-registry:
        description: Docker Hub namespace
        type: string
        required: false
        default: registry-1.docker.io
      chart-dir:
        description: Directory containing Chart.yaml
        type: string
        required: true
    secrets:
      docker-hub-username:
        description: Docker Hub username
        required: true
      docker-hub-token:
        description: Docker Hub token
        required: true

permissions:
  contents: read

jobs:
  shared-chart-build:
    name: Shared chart build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            mtweeman/hajle-silesia_app-test-config
          tags: |
            type=semver,pattern={{version}}
          flavor: |
            latest=false
      - run: |
          helm package ${{ inputs.chart-dir }} \
            --version ${{ steps.meta.outputs.version }}
          helm registry login ${{ inputs.docker-hub-registry }} \
            --username ${{ secrets.docker-hub-username }} \
            --password ${{ secrets.docker-hub-token }}
